version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      HADOOP_HOST: hadoop
  hadoop:
    image: sequenceiq/hadoop-docker:2.7.0
    ports:
      - "50070:50070"
    environment:
      - HADOOP_PREFIX=/usr/local/hadoop
